plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Curse Maven"
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }
    maven { url "https://maven.blamejared.com/" }
    maven { url 'https://maven.terraformersmc.com/' }
    flatDir { dirs 'libs' }
}

base {
    archivesName = mod_id
}

tasks.named('jar', Jar).configure {
    from('LICENSE')
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
    datagen {
        compileClasspath += main.output + main.compileClasspath
        runtimeClasspath += main.output + main.compileClasspath
    }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            sourceSet = sourceSets.datagen
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        doorsData {
            data()
            sourceSet = sourceSets.datagen
            systemProperty 'alltuttasneeds.datagen.profile', 'doors'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        bedsData {
            data()
            sourceSet = sourceSets.datagen
            systemProperty 'alltuttasneeds.datagen.profile', 'beds'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        delightsData {
            data()
            sourceSet = sourceSets.datagen
            systemProperty 'alltuttasneeds.datagen.profile', 'delights'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    datagenRuntime
    compileOnly.extendsFrom datagenRuntime
    datagenRuntimeOnly.extendsFrom datagenRuntime
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly "mezz.jei:jei-$minecraft_version-common-api:19.21.0.247"
    compileOnly "mezz.jei:jei-$minecraft_version-neoforge-api:19.21.0.247"
    localRuntime "mezz.jei:jei-$minecraft_version-neoforge:19.21.0.247"

    compileOnly "maven.modrinth:jade:15.10.5+neoforge"
    localRuntime "maven.modrinth:jade:15.10.5+neoforge"

    datagenRuntime "maven.modrinth:moonlight:1.21.1-3.3.0"
    localRuntime "maven.modrinth:moonlight:1.21.1-3.3.0"

    datagenRuntime "maven.modrinth:new_world:1.7.2"
    localRuntime "maven.modrinth:new_world:1.7.2"

    datagenRuntime "maven.modrinth:vanillabackport:rUSWdBok"
    localRuntime "maven.modrinth:vanillabackport:rUSWdBok"
    datagenRuntime "maven.modrinth:i6fiqm5y:v7P0nBi2"
    localRuntime "maven.modrinth:i6fiqm5y:v7P0nBi2"

    datagenRuntime "maven.modrinth:the-block-box:0.1.1"
    localRuntime "maven.modrinth:the-block-box:0.1.1"

    datagenRuntime "curse.maven:malum-484064:7307339"
    localRuntime "curse.maven:malum-484064:7307339"
    datagenRuntime "maven.modrinth:lodestonelib:1.8.2"
    localRuntime "maven.modrinth:lodestonelib:1.8.2"
    datagenRuntime "maven.modrinth:curios:9.5.1+1.21.1"
    localRuntime "maven.modrinth:curios:9.5.1+1.21.1"

    datagenRuntime "maven.modrinth:no-mans-land:1.5.12"
    localRuntime "maven.modrinth:no-mans-land:1.5.12"
    datagenRuntime "maven.modrinth:biolith:EAjbdreT"
    localRuntime "maven.modrinth:biolith:EAjbdreT"
    datagenRuntime "maven.modrinth:mixed-litter:1.2.2"
    localRuntime "maven.modrinth:mixed-litter:1.2.2"

    datagenRuntime "curse.maven:enderscape-536638:6738966"
    localRuntime "curse.maven:enderscape-536638:6738966"
    datagenRuntime "maven.modrinth:trimmed:1.21-3.0.0+neoforge"
    localRuntime "maven.modrinth:trimmed:1.21-3.0.0+neoforge"
    datagenRuntime "maven.modrinth:yacl:3.7.1+1.21.1-neoforge"
    localRuntime "maven.modrinth:yacl:3.7.1+1.21.1-neoforge"

    datagenRuntime "curse.maven:artsandcrafts-1034791:8041062"
    localRuntime "curse.maven:artsandcrafts-1034791:8041062"
    datagenRuntime "curse.maven:jinxedlib-1203401:6727693"
    localRuntime "curse.maven:jinxedlib-1203401:6727693"

    datagenRuntime "maven.modrinth:natures-spirit:2.2.5-1.21.1"
    localRuntime "maven.modrinth:natures-spirit:2.2.5-1.21.1"

    datagenRuntime "curse.maven:create-328085:7963363"
    localRuntime "curse.maven:create-328085:7963363"

    datagenRuntime "curse.maven:biomes-o-plenty-220318:7251965"
    localRuntime "curse.maven:biomes-o-plenty-220318:7251965"
    datagenRuntime "curse.maven:terrablender-neoforge-940057:6054947"
    localRuntime "curse.maven:terrablender-neoforge-940057:6054947"
    datagenRuntime "maven.modrinth:glitchcore:S2TfWrZR"
    localRuntime "maven.modrinth:glitchcore:S2TfWrZR"

    datagenRuntime "maven.modrinth:architects-palette:1.4.0-beta.5N"
    localRuntime "maven.modrinth:architects-palette:1.4.0-beta.5N"

    datagenRuntime "maven.modrinth:abundant-atmosphere:1.21.1-2.0.0-beta2.1"
    localRuntime "maven.modrinth:abundant-atmosphere:1.21.1-2.0.0-beta2.1"

    datagenRuntime "maven.modrinth:blueprint:8.1.0"
    localRuntime "maven.modrinth:blueprint:8.1.0"

    datagenRuntime "maven.modrinth:upgrade-aquatic:7.0.1"
    localRuntime "maven.modrinth:upgrade-aquatic:7.0.1"
    datagenRuntime "maven.modrinth:atmospheric:7.0.1"
    localRuntime "maven.modrinth:atmospheric:7.0.1"
    datagenRuntime "maven.modrinth:autumnity:6.0.1"
    localRuntime "maven.modrinth:autumnity:6.0.1"
    datagenRuntime "maven.modrinth:environmental:5.0.1"
    localRuntime "maven.modrinth:environmental:5.0.1"
    datagenRuntime "maven.modrinth:caverns-and-chasms:3.0.0"
    localRuntime "maven.modrinth:caverns-and-chasms:3.0.0"
    datagenRuntime "maven.modrinth:gallery:2.0.1"

    datagenRuntime "maven.modrinth:woodworks:4.0.2"
    localRuntime "maven.modrinth:woodworks:4.0.2"


    // Delights compat
    datagenRuntime "maven.modrinth:farmers-delight:1.21.1-1.3.2"
    localRuntime "maven.modrinth:farmers-delight:1.21.1-1.3.2"
    datagenRuntime "maven.modrinth:my-nethers-delight:1.10.4"
    localRuntime "maven.modrinth:my-nethers-delight:1.10.4"
    datagenRuntime "maven.modrinth:miners-delight:1.4.5"
    localRuntime "maven.modrinth:miners-delight:1.4.5"
    localRuntime "maven.modrinth:lodestonelib:1.8.2"
    datagenRuntime "maven.modrinth:brewin-and-chewin:4.4.0+1.21.1-neoforge"
    localRuntime "maven.modrinth:brewin-and-chewin:4.4.0+1.21.1-neoforge"

    datagenRuntime "maven.modrinth:windswept:4.0.0"
    localRuntime "maven.modrinth:windswept:4.0.0"
    localRuntime "maven.modrinth:windswept-delights:2.0.1"

    datagenRuntime "maven.modrinth:abnormals-delight:6.0.2"
    localRuntime "maven.modrinth:abnormals-delight:6.0.2"

    datagenRuntime "curse.maven:spawn-mod-935694:8507225"
    localRuntime "curse.maven:spawn-mod-935694:8507225"
    datagenRuntime "maven.modrinth:teallib:1.3.teal"
    localRuntime "maven.modrinth:teallib:1.3.teal"

    localRuntime "maven.modrinth:appleskin:3.0.9+mc1.21"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
