plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Curse Maven"
        url = uri("https://cursemaven.com")
        content {
            includeGroup("curse.maven")
        }
    }
    maven { url "https://maven.blamejared.com/" }
    maven { url 'https://maven.terraformersmc.com/' }
    flatDir { dirs 'libs' }
}

base {
    archivesName = mod_id
}

tasks.named('jar', Jar).configure {
    from('LICENSE')
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
    datagen {
        compileClasspath += main.output + main.compileClasspath
        runtimeClasspath += main.output + main.compileClasspath
    }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            sourceSet = sourceSets.datagen
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        doorsData {
            data()
            sourceSet = sourceSets.datagen
            systemProperty 'alltuttasneeds.datagen.profile', 'doors'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        bedsData {
            data()
            sourceSet = sourceSets.datagen
            systemProperty 'alltuttasneeds.datagen.profile', 'beds'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        delightsData {
            data()
            sourceSet = sourceSets.datagen
            systemProperty 'alltuttasneeds.datagen.profile', 'delights'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    datagenRuntime
    compileOnly.extendsFrom datagenRuntime
    datagenRuntimeOnly.extendsFrom datagenRuntime
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly "mezz.jei:jei-$minecraft_version-common-api:$jei_version"
    compileOnly "mezz.jei:jei-$minecraft_version-neoforge-api:$jei_version"
    localRuntime "mezz.jei:jei-$minecraft_version-neoforge:$jei_version"

    compileOnly "maven.modrinth:jade:$jade_version"
    localRuntime "maven.modrinth:jade:$jade_version"

    datagenRuntime "maven.modrinth:moonlight:$moonlight_version"
    localRuntime "maven.modrinth:moonlight:$moonlight_version"

    datagenRuntime "maven.modrinth:bountiful-fares:$bountiful_fares_version"
    localRuntime "maven.modrinth:bountiful-fares:$bountiful_fares_version"
    datagenRuntime "maven.modrinth:nexuslib:$nexuslib_version"
    localRuntime "maven.modrinth:nexuslib:$nexuslib_version"

    datagenRuntime "maven.modrinth:new_world:$new_world_version"
    localRuntime "maven.modrinth:new_world:$new_world_version"

    datagenRuntime "maven.modrinth:vanillabackport:$vanilla_backport_version"
    localRuntime "maven.modrinth:vanillabackport:$vanilla_backport_version"
    datagenRuntime "maven.modrinth:i6fiqm5y:$tuttas_doors_version"
    localRuntime "maven.modrinth:i6fiqm5y:$tuttas_doors_version"

    datagenRuntime "maven.modrinth:the-block-box:$block_box_version"
    localRuntime "maven.modrinth:the-block-box:$block_box_version"

    datagenRuntime "curse.maven:malum-484064:$malum_curseforge_file_id"
    localRuntime "curse.maven:malum-484064:$malum_curseforge_file_id"
    datagenRuntime "maven.modrinth:lodestonelib:$lodestone_version"
    localRuntime "maven.modrinth:lodestonelib:$lodestone_version"
    datagenRuntime "maven.modrinth:curios:$curios_version"
    localRuntime "maven.modrinth:curios:$curios_version"

    datagenRuntime "maven.modrinth:no-mans-land:$no_mans_land_version"
    localRuntime "maven.modrinth:no-mans-land:$no_mans_land_version"
    datagenRuntime "maven.modrinth:biolith:$biolith_version"
    localRuntime "maven.modrinth:biolith:$biolith_version"
    datagenRuntime "maven.modrinth:mixed-litter:$mixed_litter_version"
    localRuntime "maven.modrinth:mixed-litter:$mixed_litter_version"

    datagenRuntime "curse.maven:enderscape-536638:$enderscape_curseforge_file_id"
    localRuntime "curse.maven:enderscape-536638:$enderscape_curseforge_file_id"
    datagenRuntime "maven.modrinth:trimmed:$trimmed_version"
    localRuntime "maven.modrinth:trimmed:$trimmed_version"
    datagenRuntime "maven.modrinth:yacl:$yacl_version"
    localRuntime "maven.modrinth:yacl:$yacl_version"

    datagenRuntime "curse.maven:artsandcrafts-1034791:$arts_and_crafts_curseforge_file_id"
    localRuntime "curse.maven:artsandcrafts-1034791:$arts_and_crafts_curseforge_file_id"
    datagenRuntime "curse.maven:jinxedlib-1203401:$jinxedlib_curseforge_file_id"
    localRuntime "curse.maven:jinxedlib-1203401:$jinxedlib_curseforge_file_id"

    datagenRuntime "maven.modrinth:natures-spirit:$natures_spirit_version"
    localRuntime "maven.modrinth:natures-spirit:$natures_spirit_version"

    datagenRuntime "curse.maven:create-328085:$create_curseforge_file_id"
    localRuntime "curse.maven:create-328085:$create_curseforge_file_id"

    datagenRuntime "curse.maven:biomes-o-plenty-220318:$biomes_o_plenty_curseforge_file_id"
    localRuntime "curse.maven:biomes-o-plenty-220318:$biomes_o_plenty_curseforge_file_id"
    datagenRuntime "curse.maven:terrablender-neoforge-940057:$terrablender_curseforge_file_id"
    localRuntime "curse.maven:terrablender-neoforge-940057:$terrablender_curseforge_file_id"
    datagenRuntime "maven.modrinth:glitchcore:$glitchcore_version"
    localRuntime "maven.modrinth:glitchcore:$glitchcore_version"

    datagenRuntime "maven.modrinth:architects-palette:$architects_palette_version"
    localRuntime "maven.modrinth:architects-palette:$architects_palette_version"

    datagenRuntime "maven.modrinth:abundant-atmosphere:$abundant_atmosphere_version"
    localRuntime "maven.modrinth:abundant-atmosphere:$abundant_atmosphere_version"

    datagenRuntime "maven.modrinth:blueprint:$blueprint_version"
    localRuntime "maven.modrinth:blueprint:$blueprint_version"

    datagenRuntime "maven.modrinth:upgrade-aquatic:$upgrade_aquatic_version"
    localRuntime "maven.modrinth:upgrade-aquatic:$upgrade_aquatic_version"
    datagenRuntime "maven.modrinth:atmospheric:$atmospheric_version"
    localRuntime "maven.modrinth:atmospheric:$atmospheric_version"
    datagenRuntime "maven.modrinth:autumnity:$autumnity_version"
    localRuntime "maven.modrinth:autumnity:$autumnity_version"
    datagenRuntime "maven.modrinth:environmental:$environmental_version"
    localRuntime "maven.modrinth:environmental:$environmental_version"
    datagenRuntime "maven.modrinth:caverns-and-chasms:$caverns_and_chasms_version"
    localRuntime "maven.modrinth:caverns-and-chasms:$caverns_and_chasms_version"
    datagenRuntime "maven.modrinth:gallery:$gallery_version"

    datagenRuntime "maven.modrinth:woodworks:$woodworks_version"
    localRuntime "maven.modrinth:woodworks:$woodworks_version"


    // Delights compat
    datagenRuntime "maven.modrinth:farmers-delight:$farmers_delight_version"
    localRuntime "maven.modrinth:farmers-delight:$farmers_delight_version"
    datagenRuntime "maven.modrinth:my-nethers-delight:$my_nethers_delight_version"
    localRuntime "maven.modrinth:my-nethers-delight:$my_nethers_delight_version"
    datagenRuntime "maven.modrinth:miners-delight:$miners_delight_version"
    localRuntime "maven.modrinth:miners-delight:$miners_delight_version"
    datagenRuntime "maven.modrinth:brewin-and-chewin:$brewin_and_chewin_version"
    localRuntime "maven.modrinth:brewin-and-chewin:$brewin_and_chewin_version"

    datagenRuntime "maven.modrinth:windswept:$windswept_version"
    localRuntime "maven.modrinth:windswept:$windswept_version"
    localRuntime "maven.modrinth:windswept-delights:$windswept_delights_version"

    datagenRuntime "maven.modrinth:abnormals-delight:$abnormals_delight_version"
    localRuntime "maven.modrinth:abnormals-delight:$abnormals_delight_version"

    datagenRuntime "curse.maven:spawn-mod-935694:$spawn_curseforge_file_id"
    localRuntime "curse.maven:spawn-mod-935694:$spawn_curseforge_file_id"
    datagenRuntime "maven.modrinth:teallib:$teallib_version"
    localRuntime "maven.modrinth:teallib:$teallib_version"

    localRuntime "maven.modrinth:appleskin:$appleskin_version"

    localRuntime "maven.modrinth:obe:$obe_version"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = uri("${project.projectDir}/repo")
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
