org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.250
neo_version_range=[21.1.133,)
loader_version_range=[1,)

mod_id=alltuttasneeds
mod_name=All Tutta's Needs
mod_license=MIT for code; All Rights Reserved for assets
mod_version=3.4.0
mod_group_id=com.alltuttasneeds
mod_authors=SoyTutta
mod_description=A modular collection of customizable doors, beds, mattresses, blankets, meals and feasts, with optional support for other mods.

# Development and compatibility dependencies for Minecraft 1.21.1
jei_version=19.56.0.439
jade_version=15.10.6+neoforge
# Moonlight 1.21.1-3.6.4 for NeoForge
moonlight_version=BnjVBHVl
# Bountiful Fares 3.0.12
bountiful_fares_version=mobA3Cfl
# NexusLib 1.1.5
nexuslib_version=6oD2aKnX
new_world_version=1.7.3
# Vanilla Backport 1.1.7.10
vanilla_backport_version=rUSWdBok
# Tutta's Doors 1.3.3
tuttas_doors_version=v7P0nBi2
block_box_version=0.1.3

# Malum 1.8.2
malum_curseforge_file_id=7307339
lodestone_version=1.8.2
curios_version=9.5.1+1.21.1
no_mans_land_version=1.5.12
# Biolith 3.0.14
biolith_version=EAjbdreT
mixed_litter_version=1.2.2

# Enderscape 1.0.9
enderscape_curseforge_file_id=6738966
trimmed_version=1.21-3.0.0+neoforge
yacl_version=3.8.2+1.21.1-neoforge

# Arts & Crafts 1.5.4
arts_and_crafts_curseforge_file_id=8041062
# JinxedLib 1.0.4
jinxedlib_curseforge_file_id=6727693
natures_spirit_version=2.2.5-1.21.1

# Create 6.0.10
create_curseforge_file_id=7963363
# Biomes O' Plenty 21.1.0.14
biomes_o_plenty_curseforge_file_id=7251965
# TerraBlender 4.1.0.8
terrablender_curseforge_file_id=6054947
# GlitchCore 2.1.0.2
glitchcore_version=S2TfWrZR
architects_palette_version=1.4.0-beta.5N
abundant_atmosphere_version=1.21.1-2.0.0-beta2.1

blueprint_version=8.2.0
upgrade_aquatic_version=7.0.1
atmospheric_version=7.0.1
autumnity_version=6.0.1
environmental_version=5.0.1
caverns_and_chasms_version=3.0.0
gallery_version=2.0.1
woodworks_version=4.0.2

farmers_delight_version=1.21.1-1.3.4
my_nethers_delight_version=1.10.4.1
miners_delight_version=1.4.5
brewin_and_chewin_version=4.5.0+1.21.1-neoforge
windswept_version=4.0.2
windswept_delights_version=2.0.1
abnormals_delight_version=6.0.2

# Spawn 4.0.8
spawn_curseforge_file_id=8507225
teallib_version=1.3.teal
appleskin_version=3.0.9+mc1.21
# Obscure API 1.1.45 for NeoForge
obe_version=igHVZdS1
