modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="nomansland"
    type="optional"
    versionRange="[1.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="blockbox"
    type="optional"
    versionRange="[0.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="newworld"
    type="optional"
    versionRange="[1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="mynethersdelight"
    type="optional"
    versionRange="[1.8,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="enderscape"
    type="optional"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="arts_and_crafts"
    type="optional"
    versionRange="[1.5,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="natures_spirit"
    type="optional"
    versionRange="[2.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="biomesoplenty"
    type="optional"
    versionRange="[21.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="malum"
    type="optional"
    versionRange="[1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    type="optional"
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"